//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTheHandUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InTheHandUI.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        internal static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By {0}.
        /// </summary>
        internal static string ByAuthor {
            get {
                return ResourceManager.GetString("ByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointments.
        /// </summary>
        internal static string CapabilityAppointments {
            get {
                return ResourceManager.GetString("CapabilityAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your camera.
        /// </summary>
        internal static string CapabilityCamera {
            get {
                return ResourceManager.GetString("CapabilityCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contacts.
        /// </summary>
        internal static string CapabilityContacts {
            get {
                return ResourceManager.GetString("CapabilityContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone identity.
        /// </summary>
        internal static string CapabilityIdentityDevice {
            get {
                return ResourceManager.GetString("CapabilityIdentityDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your identity.
        /// </summary>
        internal static string CapabilityIdentityUser {
            get {
                return ResourceManager.GetString("CapabilityIdentityUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your music library.
        /// </summary>
        internal static string CapabilityMediaLibraryAudio {
            get {
                return ResourceManager.GetString("CapabilityMediaLibraryAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pictures library.
        /// </summary>
        internal static string CapabilityMediaLibraryPhoto {
            get {
                return ResourceManager.GetString("CapabilityMediaLibraryPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your microphone.
        /// </summary>
        internal static string CapabilityMicrophone {
            get {
                return ResourceManager.GetString("CapabilityMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your internet connection.
        /// </summary>
        internal static string CapabilityNetworking {
            get {
                return ResourceManager.GetString("CapabilityNetworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity.
        /// </summary>
        internal static string CapabilityProximity {
            get {
                return ResourceManager.GetString("CapabilityProximity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable storage.
        /// </summary>
        internal static string CapabilityRemovableStorage {
            get {
                return ResourceManager.GetString("CapabilityRemovableStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your wallet.
        /// </summary>
        internal static string CapabilityWallet {
            get {
                return ResourceManager.GetString("CapabilityWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app has permission to use:.
        /// </summary>
        internal static string PermissionsSubHeading {
            get {
                return ResourceManager.GetString("PermissionsSubHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and review.
        /// </summary>
        internal static string RateAndReview {
            get {
                return ResourceManager.GetString("RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow toast notifications.
        /// </summary>
        internal static string ToastNotifications {
            get {
                return ResourceManager.GetString("ToastNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
